# For all possible configuration options see:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/export-server"
    schedule:
      interval: "daily"
    reviewers:
      - "striezel"
    commit-message:
      prefix: "dependencies"
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "striezel"
